# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ser_identity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ser_identity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ser_identity.proto\x12\x0eserhu.identity\"\x1c\n\x0bHexacoFacet\x12\r\n\x05score\x18\x01 \x01(\x02\"\x1c\n\x0bTciSubscale\x12\r\n\x05score\x18\x01 \x01(\x02\"\x1e\n\rSchwartzValue\x12\r\n\x05score\x18\x01 \x01(\x02\"\x8a\x01\n\x10\x44\x65velopmentStage\x12\r\n\x05stage\x18\x01 \x01(\t\x12\x18\n\x10\x65rikson_conflict\x18\x02 \x01(\t\x12\x15\n\rcognitive_age\x18\x03 \x01(\x02\x12\x19\n\x11interaction_count\x18\x04 \x01(\r\x12\x1b\n\x13milestones_achieved\x18\x05 \x03(\t\"\xbb\x06\n\x11PersonalityLedger\x12\x0e\n\x06ser_id\x18\x01 \x01(\t\x12\x1a\n\x12\x63ognitive_age_days\x18\x02 \x01(\r\x12\x14\n\x0cpiaget_stage\x18\x03 \x01(\t\x12=\n\x06hexaco\x18\x04 \x03(\x0b\x32-.serhu.identity.PersonalityLedger.HexacoEntry\x12N\n\x0ftci_temperament\x18\x05 \x03(\x0b\x32\x35.serhu.identity.PersonalityLedger.TciTemperamentEntry\x12J\n\rtci_character\x18\x06 \x03(\x0b\x32\x33.serhu.identity.PersonalityLedger.TciCharacterEntry\x12\x41\n\x08schwartz\x18\x07 \x03(\x0b\x32/.serhu.identity.PersonalityLedger.SchwartzEntry\x12\x35\n\x0b\x64\x65velopment\x18\x08 \x01(\x0b\x32 .serhu.identity.DevelopmentStage\x12\x0c\n\x04name\x18\t \x01(\t\x12\x10\n\x08language\x18\n \x01(\t\x12\x14\n\x0c\x63ore_beliefs\x18\x0b \x03(\t\x12\x17\n\x0fsurface_beliefs\x18\x0c \x03(\t\x1aJ\n\x0bHexacoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.serhu.identity.HexacoFacet:\x02\x38\x01\x1aR\n\x13TciTemperamentEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.serhu.identity.TciSubscale:\x02\x38\x01\x1aP\n\x11TciCharacterEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.serhu.identity.TciSubscale:\x02\x38\x01\x1aN\n\rSchwartzEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.serhu.identity.SchwartzValue:\x02\x38\x01\x42\x16\n\x12\x63om.serhu.identityP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ser_identity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.serhu.identityP\001'
  _globals['_PERSONALITYLEDGER_HEXACOENTRY']._loaded_options = None
  _globals['_PERSONALITYLEDGER_HEXACOENTRY']._serialized_options = b'8\001'
  _globals['_PERSONALITYLEDGER_TCITEMPERAMENTENTRY']._loaded_options = None
  _globals['_PERSONALITYLEDGER_TCITEMPERAMENTENTRY']._serialized_options = b'8\001'
  _globals['_PERSONALITYLEDGER_TCICHARACTERENTRY']._loaded_options = None
  _globals['_PERSONALITYLEDGER_TCICHARACTERENTRY']._serialized_options = b'8\001'
  _globals['_PERSONALITYLEDGER_SCHWARTZENTRY']._loaded_options = None
  _globals['_PERSONALITYLEDGER_SCHWARTZENTRY']._serialized_options = b'8\001'
  _globals['_HEXACOFACET']._serialized_start=38
  _globals['_HEXACOFACET']._serialized_end=66
  _globals['_TCISUBSCALE']._serialized_start=68
  _globals['_TCISUBSCALE']._serialized_end=96
  _globals['_SCHWARTZVALUE']._serialized_start=98
  _globals['_SCHWARTZVALUE']._serialized_end=128
  _globals['_DEVELOPMENTSTAGE']._serialized_start=131
  _globals['_DEVELOPMENTSTAGE']._serialized_end=269
  _globals['_PERSONALITYLEDGER']._serialized_start=272
  _globals['_PERSONALITYLEDGER']._serialized_end=1099
  _globals['_PERSONALITYLEDGER_HEXACOENTRY']._serialized_start=779
  _globals['_PERSONALITYLEDGER_HEXACOENTRY']._serialized_end=853
  _globals['_PERSONALITYLEDGER_TCITEMPERAMENTENTRY']._serialized_start=855
  _globals['_PERSONALITYLEDGER_TCITEMPERAMENTENTRY']._serialized_end=937
  _globals['_PERSONALITYLEDGER_TCICHARACTERENTRY']._serialized_start=939
  _globals['_PERSONALITYLEDGER_TCICHARACTERENTRY']._serialized_end=1019
  _globals['_PERSONALITYLEDGER_SCHWARTZENTRY']._serialized_start=1021
  _globals['_PERSONALITYLEDGER_SCHWARTZENTRY']._serialized_end=1099
# @@protoc_insertion_point(module_scope)
