# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from serhu_orchestrator.proto import ser_identity_pb2 as ser__identity__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ser_identity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BeingServiceStub(object):
    """---------------------------------------------------------------------------
    gRPC Service – communication between Lambda (vigília) and Fargate (sono)
    ---------------------------------------------------------------------------

    Service for managing the lifecycle of a synthetic Being's personality
    using the Personality Ledger.  Designed for high-performance binary
    communication between the wakefulness (Lambda) and sleep (Fargate) modules.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLedger = channel.unary_unary(
                '/serhu.identity.BeingService/GetLedger',
                request_serializer=ser__identity__pb2.GetLedgerRequest.SerializeToString,
                response_deserializer=ser__identity__pb2.PersonalityLedger.FromString,
                _registered_method=True)
        self.RecordEvent = channel.unary_unary(
                '/serhu.identity.BeingService/RecordEvent',
                request_serializer=ser__identity__pb2.PersonalityEvent.SerializeToString,
                response_deserializer=ser__identity__pb2.RecordEventResponse.FromString,
                _registered_method=True)
        self.ReplayEvents = channel.unary_unary(
                '/serhu.identity.BeingService/ReplayEvents',
                request_serializer=ser__identity__pb2.ReplayEventsRequest.SerializeToString,
                response_deserializer=ser__identity__pb2.PersonalityLedger.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/serhu.identity.BeingService/StreamEvents',
                request_serializer=ser__identity__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=ser__identity__pb2.PersonalityEvent.FromString,
                _registered_method=True)


class BeingServiceServicer(object):
    """---------------------------------------------------------------------------
    gRPC Service – communication between Lambda (vigília) and Fargate (sono)
    ---------------------------------------------------------------------------

    Service for managing the lifecycle of a synthetic Being's personality
    using the Personality Ledger.  Designed for high-performance binary
    communication between the wakefulness (Lambda) and sleep (Fargate) modules.
    """

    def GetLedger(self, request, context):
        """Retrieve the current personality ledger for a Being.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordEvent(self, request, context):
        """Record a new event in the Being's life log.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplayEvents(self, request, context):
        """Replay the event log to reconstruct the ledger at a point in time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Stream events for a Being (server-side streaming for real-time sync).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BeingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLedger': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLedger,
                    request_deserializer=ser__identity__pb2.GetLedgerRequest.FromString,
                    response_serializer=ser__identity__pb2.PersonalityLedger.SerializeToString,
            ),
            'RecordEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordEvent,
                    request_deserializer=ser__identity__pb2.PersonalityEvent.FromString,
                    response_serializer=ser__identity__pb2.RecordEventResponse.SerializeToString,
            ),
            'ReplayEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplayEvents,
                    request_deserializer=ser__identity__pb2.ReplayEventsRequest.FromString,
                    response_serializer=ser__identity__pb2.PersonalityLedger.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=ser__identity__pb2.StreamEventsRequest.FromString,
                    response_serializer=ser__identity__pb2.PersonalityEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serhu.identity.BeingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('serhu.identity.BeingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BeingService(object):
    """---------------------------------------------------------------------------
    gRPC Service – communication between Lambda (vigília) and Fargate (sono)
    ---------------------------------------------------------------------------

    Service for managing the lifecycle of a synthetic Being's personality
    using the Personality Ledger.  Designed for high-performance binary
    communication between the wakefulness (Lambda) and sleep (Fargate) modules.
    """

    @staticmethod
    def GetLedger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/serhu.identity.BeingService/GetLedger',
            ser__identity__pb2.GetLedgerRequest.SerializeToString,
            ser__identity__pb2.PersonalityLedger.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/serhu.identity.BeingService/RecordEvent',
            ser__identity__pb2.PersonalityEvent.SerializeToString,
            ser__identity__pb2.RecordEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplayEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/serhu.identity.BeingService/ReplayEvents',
            ser__identity__pb2.ReplayEventsRequest.SerializeToString,
            ser__identity__pb2.PersonalityLedger.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/serhu.identity.BeingService/StreamEvents',
            ser__identity__pb2.StreamEventsRequest.SerializeToString,
            ser__identity__pb2.PersonalityEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
